FROM kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.6.1

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    ccache \
    cmake \
    curl \
    git \
    git-lfs \
    jq \
    libcurl3-dev \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    libjpeg-dev \
    libpng-dev \
    libopenjp2-7-dev \
    liblcms2-dev \
    libtiff-dev \
    libsndfile1 \
    ffmpeg \
    libz-dev \
    pkg-config \
    software-properties-common \
    sox \
    zlib1g-dev \
    wget \
    openmpi-bin \
    python3-dev \
    python3-opencv \
    nvtop \
    screen \
    && rm -rf /var/lib/apt/lists/*
USER $NB_UID

RUN python3 -m pip config set global.find-links \
    "https://download.pytorch.org/whl/cu113/torch_stable.html \
    https://storage.googleapis.com/jax-releases/jax_releases.html" \
    && python3 -m pip config set global.extra-index-url \
    "https://developer.download.nvidia.com/compute/redist" \
    && python3 -m pip install --no-cache-dir -U \
    albumentations \
    black \
    torch~=1.12.1 \
    pytorch-lightning[extra]~=1.7.6 \
    torchvision \
    torchaudio \
    torchtext \
    torchmetrics~=0.10.0 \
    tokenizers \
    transformers[sentencepiece]~=4.23.1 \
    datasets \
    fiftyone \
    git+https://github.com/kpu/kenlm.git \
    gradio \
    h5py \
    imutils \
    isort \
    jupyterlab \
    jupyterlab-code-formatter \
    nemo_toolkit[asr] \
    nvidia-dali-cuda110 \
    pyctcdecode

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
