FROM kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.6.1

ENV DEBIAN_FRONTEND noninteractive

USER root
ENV CUDA_VERSION 11.2
ENV NV_CUDA_REPO_URL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64
RUN curl -fsSL ${NV_CUDA_REPO_URL}/3bf863cc.pub | apt-key add - \
    && echo "deb ${NV_CUDA_REPO_URL} /" > /etc/apt/sources.list.d/cuda.list \
    && apt-get update && apt-get install -y --no-install-recommends \
    libtinfo5 \
    libncursesw5 \
    cuda-cudart-${CUDA_VERSION/./-} \
    cuda-cudart-dev-${CUDA_VERSION/./-} \
    cuda-command-line-tools-${CUDA_VERSION/./-} \
    cuda-minimal-build-${CUDA_VERSION/./-} \
    cuda-libraries-dev-${CUDA_VERSION/./-} \
    cuda-nvml-dev-${CUDA_VERSION/./-} \
    cuda-nvcc-${CUDA_VERSION/./-} \
    cuda-nvtx-${CUDA_VERSION/./-} \
    cuda-nvprof-${CUDA_VERSION/./-} \
    cuda-compat-${CUDA_VERSION/./-} \
    cuda-libraries-${CUDA_VERSION/./-} \
    libnpp-${CUDA_VERSION/./-} \
    libnpp-dev-${CUDA_VERSION/./-} \
    libcusparse-${CUDA_VERSION/./-} \
    libcusparse-dev-${CUDA_VERSION/./-} \
    libcublas-${CUDA_VERSION/./-} \
    libcublas-dev-${CUDA_VERSION/./-} \
    libcudnn8=8.1*cuda${CUDA_VERSION} \
    libcudnn8-dev=8.1*cuda${CUDA_VERSION} \
    libnccl2=2.8*cuda${CUDA_VERSION} \
    libnccl-dev=2.8*cuda${CUDA_VERSION} \
    && apt-mark hold \
    libcublas-${CUDA_VERSION/./-} \
    libcudnn8 \
    libcudnn8-dev \
    libnccl2 \
    libnccl-dev \
    && ln -s cuda-11.2 /usr/local/cuda \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    ccache \
    cmake \
    curl \
    git \
    git-lfs \
    jq \
    libboost-system-dev \
    libboost-thread-dev \
    libboost-program-options-dev \
    libboost-test-dev \
    libeigen3-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl3-dev \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    libjpeg-dev \
    libpng-dev \
    libopenjp2-7-dev \
    liblcms2-dev \
    libtiff-dev \
    libsndfile1 \
    ffmpeg \
    libz-dev \
    pkg-config \
    rsync \
    software-properties-common \
    sox \
    zlib1g-dev \
    wget \
    openmpi-bin \
    python3-dev \
    python3-opencv \
    screen \
    && rm -rf /var/lib/apt/lists/*
USER $NB_UID

RUN python3 -m pip config set global.find-links \
    "https://download.pytorch.org/whl/cu116/torch_stable.html \
    https://storage.googleapis.com/jax-releases/jax_releases.html" \
    && python3 -m pip config set global.extra-index-url \
    "https://developer.download.nvidia.com/compute/redist"
RUN python3 -m pip uninstall -y \
    pyOpenSSL \
    kfserving \
    fastai \
    && python3 -m pip install --no-cache-dir -U \
    kfp~=1.8.14 \
    kfp-server-api \
    kserve~=0.8.0
RUN python3 -m pip install --no-cache-dir -U \
    albumentations \
    black \
    torch~=1.12.1 \
    pytorch-lightning[extra]~=1.7.6 \
    torchvision \
    torchaudio \
    torchtext \
    torchmetrics~=0.10.0 \
    tokenizers \
    transformers~=4.21.2 \
    datasets \
    decord \
    fiftyone \
    git+https://github.com/kpu/kenlm.git \
    gradio \
    h5py \
    imutils \
    isort \
    jupyterlab \
    jupyterlab-code-formatter \
    nemo_toolkit[asr,nlp]~=1.12.0 \
    nvidia-dali-cuda110 \
    pyctcdecode

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
