FROM nvidia/cuda:10.2-devel-ubuntu18.04

ENV TREX_VERSION 0.25.9

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    gcc \
    g++ \
    perl \
    libdbus-1-dev \
    libleveldb-dev \
    libjsoncpp-dev \
    libjsonrpccpp-dev \
    libboost-all-dev \
    libgmp-dev \
    libreadline-dev \
    libmicrohttpd-dev \
    mesa-common-dev \
    ocl-icd-libopencl1 \
    opencl-headers \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /t-rex
RUN wget -qO t-rex.tar.gz https://github.com/trexminer/T-Rex/releases/download/${TREX_VERSION}/t-rex-${TREX_VERSION}-linux.tar.gz \
    && tar -zxf t-rex.tar.gz

ENTRYPOINT [ "/t-rex/t-rex" ]
CMD [ "--help" ]
